### ISSUE TITLE
Some of the OSC addresses do nothing.

### ISSUE THREAD

**Issue by levdog** [LanSmash/atemOSC#2]
Using an ATEM 2/ME with ATEM software control 5.1. A large number of the OSC addresses do nothing, I haven't tested them all but I will do when I get a chance, and make a list of exactly which ones do and don't work. Below is a vague list of things that aren't working.

 - All USK stuff.
 - Next transition selection.
 - Transitions

I have and ATEM 2/ME, 1/ME, Television Studio, 1/ME 4K, Production Studio 4K. Im not good with software and coding, but I will quite happily test anything needed to further the ATEM OSC project.

**Comment by levdog** [comment]
This was a false alarm. I think I must have lost my mind for a while. My offer to test things using my ATEM units still stands.

**Comment by sneat** [comment]
I was actually coming to comment on this today as I finally got to test some of the stuff over the weekend and all of the USK stuff worked correctly for me (although the OSC addresses list gave the incorrect address for the background USK). Just had to make sure to pass a value through to the USK transitions for them to work.

Glad you got it sorted and I'm sorry it took so long to get back to you.
